# Load the Visualization API and the corechart package.
# Callback that creates and populates a data table,
# instantiates the pie chart, passes in the data and
# draws it.
analysisApp = angular.module('analysisApp', [])
analysisApp.controller "ChartsController", ['$scope','$http', ($scope, $http) ->

  $scope.drawChart = ->
    # Create the data table.
    data = new (google.visualization.DataTable)
    data.addColumn 'string', 'Settimane'
    data.addColumn 'number', 'Prenotazioni'
    arr = Object.keys($scope.dates).map((key) ->
      $scope.dates[key]
    )
    console.log arr
    data.addRows arr
    # Set chart options
    options =
      'title': 'Prenotazioni per settimana'
      'width': 1000
      'height': 300
    # Instantiate and draw our chart, passing in some options.
    chart = new (google.visualization.AreaChart)(document.getElementById('chart_div'))
    chart.draw data, options
    return

  google.charts.load 'current', 'packages': [ 'corechart' ]
  # Set a callback to run when the Google Visualization API is loaded.
  google.charts.setOnLoadCallback $scope.drawChart
]

analysisApp.directive "getdata", ->
  link: (scope, element, attr, ctrl) ->
    data = (element[0].innerHTML)
    console.log data
    data = JSON.parse(data)
    scope[data.data_type] = data.data
# ---
# generated by js2coffee 2.2.0
